# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib SA24204149
#' @import Rcpp
NULL

#' @title Gibbs
#' @description Gibbs sampler
#' @param n_samples samples
#' @param n a int value
#' @param a a double value1
#' @param b a double value2
#' @return List 
#' @export
Gibbs <- function(n_samples, n, a, b) {
    .Call('_SA24204149_Gibbs', PACKAGE = 'SA24204149', n_samples, n, a, b)
}

rcpp_hello_world <- function() {
    .Call('_SA24204149_rcpp_hello_world', PACKAGE = 'SA24204149')
}

#' @useDynLib SA24204149
#' @import Rcpp
NULL

#' @title Loss Function
#' @description calculate loss funtion
#' @param ytrue true vector
#' @param ypred predicted vector
#' @param alpha weight 
#' @return loss
#' @export
LossFunction <- function(ytrue, ypred, alpha) {
    .Call('_SA24204149_LossFunction', PACKAGE = 'SA24204149', ytrue, ypred, alpha)
}

